version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg15
    container_name: text-summarizer-db
    environment:
      POSTGRES_DB: text_summarizer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/src/config/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - text-summarizer-network

  redis:
    image: redis:7-alpine
    container_name: text-summarizer-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - text-summarizer-network

volumes:
  postgres_data:
  redis_data:

networks:
  text-summarizer-network:
    driver: bridge